- name: install chirpstack-gateway-bridge
  ansible.builtin.package:
    name: chirpstack-gateway-bridge
    state: latest
  when: apt.use_chirpstack_repo
  notify:
    - restart chirpstack-gateway-bridge-basicstation

- name: install chirpstack-gateway-bridge from package_url
  ansible.builtin.apt:
    deb: "{{ chirpstack_gateway_bridge.package_url }}"
  when: not apt.use_chirpstack_repo
  notify:
    - restart chirpstack-gateway-bridge-basicstation

- name: create certs directory
  ansible.builtin.file:
    path: /etc/chirpstack-gateway-bridge/certs
    state: directory
    owner: gatewaybridge
    group: gatewaybridge
    mode: "0700"

- name: copy server cert config
  ansible.builtin.template:
    src: server-cert.json
    dest: /etc/chirpstack-gateway-bridge/certs/server-cert.json
    owner: gatewaybridge
    group: gatewaybridge
    mode: "0600"

- name: generate server certificate
  ansible.builtin.shell: "cfssl gencert -ca /etc/chirpstack-certs/ca.pem -ca-key /etc/chirpstack-certs/ca-key.pem -config /etc/chirpstack-certs/ca-config.json -profile server server-cert.json | cfssljson -bare /etc/chirpstack-gateway-bridge/certs/server"
  args:
    chdir: /etc/chirpstack-gateway-bridge/certs
  notify:
    - restart chirpstack-gateway-bridge-basicstation

- name: copy ca cert
  ansible.builtin.copy:
    src: /etc/chirpstack-certs/ca.pem
    dest: /etc/chirpstack-gateway-bridge/certs/ca.pem
    remote_src: "yes"
    owner: gatewaybridge
    group: gatewaybridge
    mode: "0600"
  notify:
    - restart chirpstack-gateway-bridge-basicstation

- name: set certificate permissions
  ansible.builtin.file:
    path: /etc/chirpstack-gateway-bridge/certs
    state: directory
    recurse: "yes"
    owner: gatewaybridge
    group: gatewaybridge
    mode: "0600"

- name: set certificate directory permissions
  ansible.builtin.file:
    path: /etc/chirpstack-gateway-bridge/certs
    state: directory
    owner: gatewaybridge
    group: gatewaybridge
    mode: "0700"

- name: add systemd service
  ansible.builtin.template:
    src: chirpstack-gateway-bridge-basicstation.service
    dest: /lib/systemd/system/chirpstack-gateway-bridge-basicstation.service
  notify:
    - reload systemctl daemon

- name: copy configuration
  ansible.builtin.template:
    src: "chirpstack-gateway-bridge-basicstation-{{ chirpstack_gateway_bridge_basicstation.region }}.toml"
    dest: /etc/chirpstack-gateway-bridge/chirpstack-gateway-bridge-basicstation.toml
    owner: gatewaybridge
    group: gatewaybridge
    mode: "0640"
  notify:
    - restart chirpstack-gateway-bridge-basicstation

- name: start chirpstack-gateway-bridge-basicstation on boot
  ansible.builtin.service:
    name: chirpstack-gateway-bridge-basicstation
    state: started
    enabled: true
