- name: install packages
  package: name={{ item }} state=latest
  with_items:
    - python3-psycopg2
    - postgresql
    - acl

- name: start postgresql on boot
  service:
    name: postgresql
    state: started
    enabled: yes

- name: create chirpstack role
  postgresql_user:
    name: "{{ chirpstack.postgresql.user }}"
    password: "{{ chirpstack.postgresql.password }}"
    role_attr_flags: LOGIN
  become_user: postgres

- name: create chirpstack database
  postgresql_db:
    name: "{{ chirpstack.postgresql.db }}"
    owner: "{{ chirpstack.postgresql.user }}"
  become_user: postgres

- name: create trgm extension for chirpstack database
  postgresql_ext:
    db: "{{ chirpstack.postgresql.db }}"
    name: pg_trgm
  become_user: postgres

- name: create hstore extension for chirpstack database
  postgresql_ext:
    db: "{{ chirpstack.postgresql.db }}"
    name: hstore
  become_user: postgres
