- name: install redis
  ansible.builtin.package:
    name: redis-server
    state: latest

- name: start redis on boot
  ansible.builtin.service:
    name: redis-server
    state: started
    enabled: yes
