- name: install chirpstack-gateway-bridge
  ansible.builtin.package:
    name: chirpstack-gateway-bridge
    state: latest
  when: apt.use_chirpstack_repo
  notify:
    - restart chirpstack-gateway-bridge

- name: install chirpstack-gateway-bridge from package_url
  ansible.builtin.apt:
    deb: "{{ chirpstack_gateway_bridge.package_url }}"
  when: not apt.use_chirpstack_repo
  notify:
    - restart chirpstack-gateway-bridge

- name: copy configuration
  ansible.builtin.template:
    src: chirpstack-gateway-bridge.toml
    dest: /etc/chirpstack-gateway-bridge/chirpstack-gateway-bridge.toml
    owner: gatewaybridge
    group: gatewaybridge
    mode: "0640"
  notify:
    - restart chirpstack-gateway-bridge

- name: start chirpstack-gateway-bridge on boot
  ansible.builtin.service:
    name: chirpstack-gateway-bridge
    state: started
    enabled: "yes"
