- name: create directory
  ansible.builtin.file:
    path: /etc/chirpstack-certs
    state: directory
    owner: root
    group: root
    mode: "0700"

- name: copy configuration
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/chirpstack-certs/{{ item }}"
    owner: root
    group: root
    mode: "0600"
  with_items:
    - ca-config.json
    - ca-csr.json

- name: generate chirpstack ca
  ansible.builtin.shell: "cfssl gencert -initca ca-csr.json | cfssljson -bare /etc/chirpstack-certs/ca"
  args:
    chdir: /etc/chirpstack-certs
    creates: /etc/chirpstack-certs/ca.pem
