# See https://www.chirpstack.io/gateway-bridge/install/config/ for a full
# configuration example and documentation.

[integration.mqtt.auth.generic]
servers=["tcp://localhost:1883"]
username=""
password=""

[integration.mqtt]
event_topic_template="{{ chirpstack_gateway_bridge_basicstation.region }}{% raw %}/gateway/{{ .GatewayID }}/event/{{ .EventType }}{% endraw %}"
state_topic_template="{{ chirpstack_gateway_bridge_basicstation.region }}{% raw %}/gateway/{{ .GatewayID }}/state/{{ .StateType }}{% endraw %}"
command_topic_template="{{ chirpstack_gateway_bridge_basicstation.region }}{% raw %}/gateway/{{ .GatewayID }}/command/#{% endraw %}"

[backend]
type="basic_station"

  [backend.basic_station]
  bind=":3001"
  tls_cert="/etc/chirpstack-gateway-bridge/certs/server.pem"
  tls_key="/etc/chirpstack-gateway-bridge/certs/server-key.pem"
  ca_cert="/etc/chirpstack-gateway-bridge/certs/ca.pem"

  region="AU915"
  frequency_min=915000000
  frequency_max=928000000


  [[backend.basic_station.concentrators]]

    [backend.basic_station.concentrators.multi_sf]
    frequencies=[
      923200000,
      923400000,
      923600000,
      923800000,
      924000000,
      924200000,
      924400000,
      924600000,
    ]
  
    [backend.basic_station.concentrators.lora_std]
    frequency=923900000
    bandwidth=500000  
    spreading_factor=8
