# See https://www.chirpstack.io/gateway-bridge/install/config/ for a full
# configuration example and documentation.

[integration.mqtt.auth.generic]
servers=["tcp://localhost:1883"]
username=""
password=""

[integration.mqtt]
event_topic_template="{{ chirpstack_gateway_bridge_basicstation.region }}{% raw %}/gateway/{{ .GatewayID }}/event/{{ .EventType }}{% endraw %}"
state_topic_template="{{ chirpstack_gateway_bridge_basicstation.region }}{% raw %}/gateway/{{ .GatewayID }}/state/{{ .StateType }}{% endraw %}"
command_topic_template="{{ chirpstack_gateway_bridge_basicstation.region }}{% raw %}/gateway/{{ .GatewayID }}/command/#{% endraw %}"

[backend]
type="basic_station"

  [backend.basic_station]
  bind=":3001"
  tls_cert="/etc/chirpstack-gateway-bridge/certs/server.pem"
  tls_key="/etc/chirpstack-gateway-bridge/certs/server-key.pem"
  ca_cert="/etc/chirpstack-gateway-bridge/certs/ca.pem"

  region="US915"
  frequency_min=470000000
  frequency_max=510000000


  [[backend.basic_station.concentrators]]

    [backend.basic_station.concentrators.multi_sf]
    frequencies=[
      478300000,
      478500000,
      478700000,
      478900000,
      479100000,
      479300000,
      479500000,
      479700000,
    ]
