# iptable configuration
#
# All ports will be blocked, except the ports listed below.
iptables:
  accept:
    -
      port: 22
      source: 0.0.0.0/0
      protocol: tcp
    -
      port: 80
      source: 0.0.0.0/0
      protocol: tcp
    -
      port: 443
      source: 0.0.0.0/0
      protocol: tcp
    -
      port: 8883
      source: 0.0.0.0/0
      protocol: tcp
    -
      port: 3001
      source: 0.0.0.0/0
      protocol: tcp
    -
      port: 1700
      source: 0.0.0.0/0
      protocol: udp

# Apt configuration.
apt:
  # Use ChirpStack repository.
  # If set to false, you must specify a package_url variable in the ChirpStack
  # components below. With the ChirpStack repo enabled, Ansible will always
  # install the latest version.
  use_chirpstack_repo: true

# Mosquitto configuration
mosquitto:
  # the full domain by which the MQTT broker is reachable
  # e.g. subdomain.example.com
  fqdn: localhost

# ChirpStack Gateway Bridge configuration (UDP)
chirpstack_gateway_bridge:
  # Region.
  # This is used as MQTT topic prefix, and must match one of the available
  # regions that are configured in the chirpstack.toml configuration file.
  region: eu868

# ChirpStack Gateway Bridge configuration (Basics Station)
chirpstack_gateway_bridge_basicstation:
  # Region.
  # This defines the configuration file that will be copied from the
  # roles/chirpstack-gateway-bridge-basicstation/templates directory.
  # The file copied will be equal to:
  # chirpstack-gateway-bridge-basicstation-[region].toml
  region: eu868

  # The full domain by which the ChirpStack Gateway Bridge Basics Station
  # backend is available.
  # e.g. subdomain.example.com
  fqdn: localhost

# ChirpStack configuration.
chirpstack:
  # The full domain by which ChirpStack is reachable.
  # e.g. subdomain.example.com
  fqdn: localhost

  # If enabled, a Let's Encrypt certificate will be configured. Else a
  # self-signed certificate will be used.
  letsencrypt:
    email: info@example.com
    request: false

  # API configuration.
  api:
    # You must replace this value!
    # To generate random secret:
    # openssl rand -base64 32
    secret: ReplaceMe

  # PostgreSQL database credentials.
  # The role and database will be created by Ansible.
  postgresql:
    db: chirpstack
    user: chirpstack
    password: chirpstack
    host: localhost
