# iptable configuration
iptables:
  accept:
    -
      port: 22
      source: 0.0.0.0/0
      protocol: tcp
    -
      port: 80
      source: 0.0.0.0/0
      protocol: tcp
    -
      port: 443
      source: 0.0.0.0/0
      protocol: tcp
    -
      port: 8883
      source: 0.0.0.0/0
      protocol: tcp
    -
      port: 1700
      source: 0.0.0.0/0
      protocol: udp

# Mosquitto configuration
mosquitto:
  fqdn: localhost

# ChirpStack Gateway Bridge configuration
chirpstack_gateway_bridge:
  region: eu868

# ChirpStack configuration.
chirpstack:
  fqdn: localhost
  letsencrypt:
    email: info@example.com
    request: false
  api:
    # You must replace this value!
    # To generate random secret:
    # openssl rand -base64 32
    secret: ReplaceMe
  postgresql:
    db: chirpstack
    user: chirpstack
    password: chirpstack
