- name: upgrade installed packages
  ansible.builtin.apt:
    update_cache: 'yes'
    upgrade: 'yes'

- name: install packages
  ansible.builtin.package: name={{ item }} state=latest
  with_items:
    - apt-transport-https
    - iptables-persistent
    - sudo
    - gpg
    - golang-cfssl

- name: import ChirpStack gpg key
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: 1CE2AFD36DBCCA00

- name: add ChirpStack deb repository
  ansible.builtin.apt_repository:
    repo: deb https://artifacts.chirpstack.io/packages/4.x/deb stable main
  when: apt.use_chirpstack_repo
