- name: reload systemctl daemon
  systemd:
    daemon_reload: true

- name: restart chirpstack-gateway-bridge-basicstation
  service:
    name: chirpstack-gateway-bridge-basicstation
    state: restarted
