- name: reload systemctl daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart chirpstack-gateway-bridge-basicstation
  ansible.builtin.service:
    name: chirpstack-gateway-bridge-basicstation
    state: restarted
