- name: install packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  with_items:
    - certbot
    - python3-certbot-nginx

- name: setup renew cron
  ansible.builtin.cron:
    name: "certbot renew"
    minute: "0"
    hour: "0"
    job: "certbot renew > /dev/null"
