# For a full configuration example, see:
# https://www.chirpstack.io/docs/chirpstack-gateway-bridge/configuration.html

[integration.mqtt]
  event_topic_template="{{ chirpstack_gateway_bridge.region }}/{% raw %}gateway/{{ .GatewayID }}/event/{{ .EventType }}{% endraw %}"
  state_topic_template="{{ chirpstack_gateway_bridge.region }}/{% raw %}gateway/{{ .GatewayID }}/state/{{ .StateType }}{% endraw %}"
  command_topic_template="{{ chirpstack_gateway_bridge.region }}/{% raw %}gateway/{{ .GatewayID }}/command/#{% endraw %}"

  [integration.mqtt.auth.generic]
    server="tcp://127.0.0.1:1883"
